// <auto-generated />
using System;
using CashFlow.Transactions.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashFlow.Transactions.API.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    partial class TransactionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CashFlow.Transactions.API.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_Transactions_Date");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Transactions_Type");

                    b.HasIndex("Date", "Type")
                        .HasDatabaseName("IX_Transactions_Date_Type");

                    b.ToTable("Transactions", "transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Amount = 8500.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Salário março",
                            Type = "Credit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Amount = 1200.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Freelance - projeto site institucional",
                            Type = "Credit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Amount = 350.75m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dividendos FII MXRF11",
                            Type = "Credit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Amount = 500.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Consultoria mensal - cliente ABC",
                            Type = "Credit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Amount = 189.90m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cashback cartão de crédito",
                            Type = "Credit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Amount = 8500.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Salário fevereiro",
                            Type = "Credit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Amount = 750.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Freelance - identidade visual",
                            Type = "Credit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Amount = 412.30m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rendimento CDB 90 dias",
                            Type = "Credit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Amount = 2100.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aluguel março",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            Amount = 480.50m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Supermercado quinzenal",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            Amount = 220.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Combustível mensal",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            Amount = 399.90m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plano de saúde",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            Amount = 199.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Curso .NET Avançado - Udemy",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            Amount = 89.90m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Netflix + Spotify",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            Amount = 312.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Conta de luz e água",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000016"),
                            Amount = 1450.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nota fiscal fornecedor TechParts",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000017"),
                            Amount = 560.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "DAS Simples Nacional março",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000018"),
                            Amount = 265.40m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Supermercado quinzenal",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000019"),
                            Amount = 130.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Uber e transporte público",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            Amount = 350.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Jantar aniversário - restaurante",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000021"),
                            Amount = 2100.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aluguel fevereiro",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000022"),
                            Amount = 510.20m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Supermercado",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000023"),
                            Amount = 399.90m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plano de saúde",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000024"),
                            Amount = 560.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "DAS Simples Nacional fevereiro",
                            Type = "Debit"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000025"),
                            Amount = 175.00m,
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Date = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manutenção notebook",
                            Type = "Debit"
                        });
                });

            modelBuilder.Entity("CashFlow.Transactions.API.Domain.Entities.TransactionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_TransactionCategories_Name");

                    b.ToTable("TransactionCategories", "transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Salário mensal e benefícios",
                            IsActive = true,
                            Name = "Salário"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Receitas de trabalhos autônomos e prestação de serviços",
                            IsActive = true,
                            Name = "Freelance"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Rendimentos de aplicações, dividendos e renda variável",
                            IsActive = true,
                            Name = "Investimentos"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Receitas diversas não classificadas",
                            IsActive = true,
                            Name = "Outras Receitas"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Description = "Supermercado, restaurantes, delivery e refeições",
                            IsActive = true,
                            Name = "Alimentação"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Description = "Combustível, aplicativos, transporte público e manutenção veicular",
                            IsActive = true,
                            Name = "Transporte"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Description = "Aluguel, condomínio, IPTU, água, luz e gás",
                            IsActive = true,
                            Name = "Moradia"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Description = "Plano de saúde, consultas, exames e medicamentos",
                            IsActive = true,
                            Name = "Saúde"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Description = "Mensalidades, cursos, livros e treinamentos",
                            IsActive = true,
                            Name = "Educação"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Description = "Entretenimento, viagens, streaming e assinaturas",
                            IsActive = true,
                            Name = "Lazer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Description = "Pagamentos a fornecedores e parceiros comerciais",
                            IsActive = true,
                            Name = "Fornecedores"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Description = "DAS, DARF, ISS, IOF e demais obrigações fiscais",
                            IsActive = true,
                            Name = "Impostos e Taxas"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Description = "Despesas diversas não classificadas",
                            IsActive = true,
                            Name = "Outras Despesas"
                        });
                });

            modelBuilder.Entity("CashFlow.Transactions.API.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("CashFlow.Transactions.API.Domain.Entities.TransactionCategory", null)
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CashFlow.Transactions.API.Domain.Entities.TransactionCategory", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
