// <auto-generated />
using System;
using CashFlow.Consolidation.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashFlow.Consolidation.API.Migrations
{
    [DbContext(typeof(ConsolidationDbContext))]
    partial class ConsolidationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CashFlow.Consolidation.API.Domain.Entities.DailyBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalCredits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebits")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("IX_DailyBalances_Date");

                    b.ToTable("DailyBalances", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Date = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 8500.00m,
                            TotalDebits = 2100.00m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Date = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 0.00m,
                            TotalDebits = 510.20m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Date = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 0.00m,
                            TotalDebits = 399.90m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Date = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 750.00m,
                            TotalDebits = 560.00m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Date = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 412.30m,
                            TotalDebits = 0.00m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Date = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 0.00m,
                            TotalDebits = 175.00m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 8500.00m,
                            TotalDebits = 2100.00m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            Date = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 0.00m,
                            TotalDebits = 480.50m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            Date = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 0.00m,
                            TotalDebits = 220.00m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000010"),
                            Date = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 1200.00m,
                            TotalDebits = 399.90m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000011"),
                            Date = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 0.00m,
                            TotalDebits = 199.00m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000012"),
                            Date = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 0.00m,
                            TotalDebits = 89.90m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000013"),
                            Date = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 350.75m,
                            TotalDebits = 0.00m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000014"),
                            Date = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 0.00m,
                            TotalDebits = 312.00m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000015"),
                            Date = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 500.00m,
                            TotalDebits = 1450.00m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000016"),
                            Date = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 0.00m,
                            TotalDebits = 560.00m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000017"),
                            Date = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 189.90m,
                            TotalDebits = 265.40m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000018"),
                            Date = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 0.00m,
                            TotalDebits = 130.00m
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000019"),
                            Date = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TotalCredits = 0.00m,
                            TotalDebits = 350.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
